<?php

return array (
  'failed' => 'These credentials do not match our records.',
  'throttle' => 'Too many login attempts. Please try again in :seconds seconds.',
  'signin' => 'Sign in',
  'signup' => 'Sign up',
  'remember' => 'Remember',
  'lost_password' => 'Lost password?',
  'create_account' => 'Create account',
  'title_login' => 'Login to Kendozone',
  'title_register' => 'Register to Kendozone',
  'register' => 'Register',
  'registered' => 'Registered',
  'username_tip' => 'Username must only contains letters and numbers without spaces',
  'email_tip' => 'Please enter your email adress',
  'password_tip' => 'Password must have at least 6 characters length',
  'password_confirmation' => 'Password ( Confirmation )',
  'password_confirmation2' => 'Confirm your password',
  'choose_username' => 'Choose your username',
  'create_password' => 'Create your password',
  'repeat_password' => 'Repeat the password',
  'your_email' => 'Your Email',
  'repeat_email' => 'Repeat the email',
  'back_to_login_form' => 'Login',
  'we_will_send_instructions' => 'We will send you instructions in an email',
  'password_recovery' => 'Password Recovery',
  'send_password' => 'Send Password',
  'reset_password' => 'Reset Password',
  'check_your_email' => 'We sent you an email with an activation link',
  'account_already_exists' => 'We already have a strong user registered with this email',
  'account_not_activated' => 'Account is not activated. Please check your email',
  'credentials' => 'Please fill the fields',
  'signin_with' => 'Or signin with',
  'no_account' => 'Still no account?',
  'tx_for_confirm' => 'Thanks for activating your account',
  'registration_completed' => 'Registration completed',
  'user_dont_exist' => 'Hansoku nikkai! There is no user registered with this email',
  'go_to_password_reset' => 'Click the link to reset your password',
  'password_reset_successfull' => 'Password resetted!',
  'enter_new_passwords' => 'Enter new password',
  'enter_new_passwords_description' => 'Confirm your new password',
  'fb_is_not_sharing_email' => 'You are not sharing you email in Facebook. Share your email in Facebook settings or click SIGN UP',
);