<?php

return array (
  'federation' => 'Federación|Federaciones',
  'federation.president' => 'Presidente',
  'federation.vicepresident' => 'Vice Presidente',
  'federation.secretary' => 'Secretario',
  'federation.treasurer' => 'Tesorero',
  'federation.admin' => 'Administrador',
  'federation.address' => 'Dirección',
  'federation.phone' => 'Teléfono',
  'federation.no_user_in_this_country' => 'No hay usuarios registrados en este país',
  'no_federation' => 'Sin federación ',
  'association' => 'Asociación|Asociaciones',
  'association.president' => 'Presidente',
  'association.address' => 'Dirección',
  'association.phone' => 'Teléfono',
  'association.no_user_in_this_country' => 'No hay usuarios registrados en este país',
  'association.add' => 'Agregar Asociación',
  'no_association_yet' => 'Aún no hay asociaciaciones creadas en esta federación',
  'add_new_association' => 'Agregar una nueva asociación',
  'no_association' => 'Sin asociación ',
  'club' => 'Club|Clubs',
  'club.president' => 'Presidente',
  'club.address' => 'Dirección',
  'club.phone' => 'Teléfono',
  'club.no_user_in_this_country' => 'No hay usuarios registrados en este país',
  'where_do_you_practice' => '¿En donde prácticas?',
  'select_field' => 'Selecciona un campo',
  'no_association_available' => 'No existen asociaciones en esta federación',
  'no_club_available' => 'No existen clubes en esta asociación',
);