<?php

return array (
  'failed' => '認証情報と一致するレコードがありません。',
  'throttle' => 'ログインの試行回数が多すぎます。:seconds 秒後にお試しください。',
  'signin' => 'ログイン',
  'signup' => 'サインアップ',
  'remember' => '保存する',
  'lost_password' => 'パスワードを忘れちゃったんですか?',
  'create_account' => 'アカウントを作成',
  'title_login' => 'Kendozoneにログイン',
  'title_register' => 'Kendozoneに登録',
  'register' => '登録する',
  'registered' => '登録完了',
  'username_tip' => 'ユーザー名は字と数だけを入力してください',
  'email_tip' => 'あなたのメールアドレスを入力してください',
  'password_tip' => 'パスワードは英数字六桁以上を設定してください',
  'password_confirmation' => 'パスワードの確認',
  'password_confirmation2' => 'パスワードの確認をしてください',
  'choose_username' => 'ユーザー名を入力してください',
  'create_password' => 'パスワードを作成してください',
  'repeat_password' => 'もう一度パスワードを入力してください',
  'your_email' => 'あなたのメールアドレスを入力してください',
  'repeat_email' => 'もう一度あなたのメールアドレスを入力してください',
  'back_to_login_form' => 'ログイン',
  'we_will_send_instructions' => 'あなたに電子メールで設定手順をお送りします',
  'password_recovery' => 'パスワードの復元',
  'send_password' => 'パスワードの送信',
  'reset_password' => 'パスワードの再設定',
  'check_your_email' => 'あなたの電子メールアドレスにリンク先をお送りしました',
  'account_already_exists' => 'この電子メールはすでに他のユーザーによって登録されています',
  'account_not_activated' => 'アカウントが有効ではありません。電子メールを確認してください',
  'credentials' => '必要な情報を全て入力してください',
  'signin_with' => 'もしくはこちらからサインイン',
  'no_account' => 'アカウントがまだない場合',
  'tx_for_confirm' => 'アカウントが有効になりました。ありがとうございました!',
  'registration_completed' => '登録が完了しました',
  'user_dont_exist' => '反則二回！この電子メールでのユーザー登録がありません ',
  'go_to_password_reset' => 'リンクをクリックしてパスワードを再設定してください',
  'password_reset_successfull' => 'パスワードが再設定されました!',
  'enter_new_passwords' => '新しいパスワードを入力してください',
  'enter_new_passwords_description' => '新しいパスワードを確認してください',
  'fb_is_not_sharing_email' => 'Facebookであなたのメールを共有していません。 Facebookの設定でメールを共有するか、[サインアップ]　を　クリックしてください。',
);