<?php

return array (
  'federation' => 'Fédération|Fédérations',
  'federation.president' => 'Président',
  'federation.vicepresident' => 'Vice président',
  'federation.secretary' => 'Secrétaire',
  'federation.treasurer' => 'Trésorier',
  'federation.admin' => 'Administrateur',
  'federation.address' => 'Adresse',
  'federation.phone' => 'Téléphone',
  'federation.no_user_in_this_country' => 'Aucun utilisateur enregistré dans ce pays',
  'no_federation' => 'Pas de fédération',
  'association' => 'Association|Associations',
  'association.president' => 'Président',
  'association.address' => 'Adresse',
  'association.phone' => 'Téléphone',
  'association.no_user_in_this_country' => 'Aucun utilisateur enregistré dans ce pays',
  'association.add' => 'Ajouter une association',
  'no_association_yet' => 'Toujours aucune associations dans cette fédération',
  'add_new_association' => 'Ajouter une nouvelle association',
  'no_association' => 'Pas d\'association',
  'club' => 'Club|Clubs',
  'club.president' => 'Président',
  'club.address' => 'Adresse',
  'club.phone' => 'Téléphone',
  'club.no_user_in_this_country' => 'Aucun utilisateur enregistré dans ce pays',
  'where_do_you_practice' => 'Où vous entraînez-vous?',
  'select_field' => 'Sélectionnez une option',
  'no_association_available' => 'Pas d\'association dans cette fédération',
  'no_club_available' => 'Pas de club dans cette association',
);